<?php
// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
$ch = curl_init();

curl_setopt($ch, CURLOPT_URL, 'https://api.openai.com/v1/completions');
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_POST, 1);
$postdata=array(
    "model"=> "text-davinci-003",
    "prompt"=> "Say this is a test",
    "max_tokens"=> 7,
    "temperature"=> 0,
    "top_p"=> 1,
    "n"=>1,
    "stream"=> false,
    "logprobs"=>null,
    "stop"=> "\n"
  
  );
 $postdata=json_encode($postdata);
curl_setopt($ch, CURLOPT_POSTFIELDS, $postdata);

$headers = array();
$headers[] = 'Content-Type: application/json';
$headers[] = 'Authorization:Bearer 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';
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

$result = curl_exec($ch);
if (curl_errno($ch)) {
    echo 'Error:' . curl_error($ch);
}
curl_close($ch);
$result=json_decode($result,true);
echo '<pre>';
print_r($result);

